name: kelicap
description: >
  Kelicap Web Application Framework.
  A fast and productive web framework that is a derivative of AngularDart which is syntatically similar to Angular 16.
version: 1.0.0
repository: https://github.com/dukefirehawk/kelicap

environment:
  sdk: ">=3.12.0 <4.0.0"

resolution: workspace

dependencies:
  # analyzer: ^13.0.0
  build: ^4.0.0
  built_collection: ^5.1.1
  #build_modules: ^5.0.12
  build_web_compilers: ^4.6.0
  built_value: ^8.4.3
  collection: ^1.17.0
  sanitize_html: ^2.1.0
  intl: ^0.20.0
  meta: ^1.8.0
  kelicap_ast: ^1.0.0
  kelicap_common: ^1.0.0
  kelicap_compiler: ^1.0.0
  stream_transform: ^2.1.0
  logging: ^1.3.0
  web: ^1.1.1

dev_dependencies:
  lints: ^6.0.0
