name: kelicap_workspace

environment:
  sdk: ">=3.13.0 <4.0.0"

workspace:
  - ast
  - common
  - observable
  - compiler
  - kelicap
  - kelicap_test
  - forms
  - router
  - _tests
  - kelicap_cli
  #- examples/hello_world
  #- _tests

dev_dependencies:
  melos: ^8.5.0
  lints: ^6.0.0

melos:
  # All the content of your previous melos.yaml file goes here
  # (e.g., scripts, command configs, etc.)
