name: kelicap_common
description: >
  The Kelicap common library.
  Common functions, types, and classes used by Kelicap and Kelicap Compiler.
version: 1.1.1
repository: https://github.com/dukefirehawk/kelicap
issue_tracker: https://github.com/dukefirehawk/kelicap/issues
documentation: https://github.com/dukefirehawk/kelicap-docs

environment:
  sdk: ">=3.13.0 <4.0.0"

resolution: workspace

dependencies:
  web: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.22.2
