name: kelicap_router
description: >
  Router components for Kelicap framework.
  Offering declarative routing, dynamic route matching, and etc.
version: 1.1.1
repository: https://github.com/dukefirehawk/kelicap
issue_tracker: https://github.com/dukefirehawk/kelicap/issues
documentation: https://github.com/dukefirehawk/kelicap-docs

environment:
  sdk: ">=3.13.0 <4.0.0"

resolution: workspace

dependencies:
  collection: ^1.17.0
  kelicap: ^1.0.0
  web: ^1.1.1
  
dev_dependencies:
  async: ^2.10.0
  build_runner: ^2.3.3
  build_test: ^3.0.0
  build_web_compilers: ^4.6.0
  lints: ^6.0.0
  mockito: ^5.3.2
  kelicap_test: ^1.0.0
  test: ^1.22.2
